'use client';

import { useState } from 'react';
import { useSceneStore, SceneTheme } from '@/store/scene-store';

interface Recommendation {
  theme: string;
  type: string;
  description: string;
  colorScheme: string[];
  suggestedMaterials: string[];
  estimatedCost: number;
  reasoning: string;
}

interface Props {
  recommendations: Recommendation[];
  loading?: boolean;
}

export function RecommendationPanel({ recommendations, loading }: Props) {
  const setTheme = useSceneStore((s) => s.setTheme);
  const [appliedTheme, setAppliedTheme] = useState<string | null>(null);

  if (loading) {
    return (
      <div className="space-y-4 p-4">
        {[1, 2, 3].map((i) => (
          <div key={i} className="animate-pulse rounded-xl bg-gray-100 h-40" />
        ))}
      </div>
    );
  }

  const handleApplyTheme = (rec: Recommendation) => {
    const theme: SceneTheme = {
      name: rec.theme,
      colorPalette: rec.colorScheme,
      materials: rec.suggestedMaterials,
      lighting: 'warm',
    };
    setTheme(theme);
    setAppliedTheme(rec.theme);
  };

  return (
    <div className="space-y-4 p-4">
      <h2 className="text-lg font-semibold text-gray-900">AI Recommendations</h2>
      <p className="text-sm text-gray-500">3 design alternatives generated by Bedrock Claude</p>

      {recommendations.map((rec, index) => (
        <div
          key={rec.theme}
          className={`rounded-xl border p-4 transition-all ${
            appliedTheme === rec.theme
              ? 'border-amber-500 bg-amber-50 shadow-md'
              : 'border-gray-200 bg-white hover:border-amber-300 hover:shadow-sm'
          }`}
        >
          <div className="flex items-start justify-between">
            <div>
              <h3 className="font-semibold text-gray-900">{rec.theme}</h3>
              <span className="text-xs text-gray-500 capitalize">{rec.type.replace(/_/g, ' ')}</span>
            </div>
            <span className="text-sm font-medium text-gray-700">
              ${rec.estimatedCost.toLocaleString()}
            </span>
          </div>

          <p className="mt-2 text-sm text-gray-600">{rec.description}</p>

          {/* Color swatches */}
          <div className="mt-3 flex gap-2">
            {rec.colorScheme.map((color, i) => (
              <div
                key={i}
                className="h-6 w-6 rounded-full border border-gray-200 shadow-sm"
                style={{ backgroundColor: color }}
                title={color}
              />
            ))}
          </div>

          {/* Materials */}
          <div className="mt-2 flex flex-wrap gap-1">
            {rec.suggestedMaterials.map((mat) => (
              <span key={mat} className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
                {mat}
              </span>
            ))}
          </div>

          {/* Apply button */}
          <button
            onClick={() => handleApplyTheme(rec)}
            className={`mt-3 w-full rounded-lg px-3 py-2 text-sm font-medium transition-colors ${
              appliedTheme === rec.theme
                ? 'bg-amber-600 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-amber-100'
            }`}
          >
            {appliedTheme === rec.theme ? '✓ Applied' : 'Apply Theme'}
          </button>
        </div>
      ))}
    </div>
  );
}
