'use client';

import { useState } from 'react';
import { useSceneStore, SceneTheme } from '@/store/scene-store';

interface Recommendation {
  theme: string;
  type: string;
  description: string;
  colorScheme: string[];
  suggestedMaterials: string[];
  estimatedCost: number;
  reasoning: string;
}

interface Props {
  recommendations: Recommendation[];
  loading?: boolean;
}

export function RecommendationPanel({ recommendations, loading }: Props) {
  const setTheme = useSceneStore((s) => s.setTheme);
  const [appliedTheme, setAppliedTheme] = useState<string | null>(null);

  if (loading) {
    return (
      <div className="space-y-4 p-4">
        {[1, 2, 3].map((i) => (
          <div key={i} className="animate-pulse rounded-xl bg-gray-100 h-40" />
        ))}
      </div>
    );
  }

  const handleApplyTheme = (rec: Recommendation) => {
    const theme: SceneTheme = {
      name: rec.theme,
      colorPalette: rec.colorScheme,
      materials: rec.suggestedMaterials,
      lighting: 'warm',
    };
    setTheme(theme);
    setAppliedTheme(rec.theme);
  };

  return (
    <div className="space-y-4 p-4">
      <h2 className="text-lg font-semibold text-[rgb(var(--ink))]">AI Recommendations</h2>
      <p className="text-sm text-[rgb(var(--muted))]">3 design alternatives generated by Bedrock Claude</p>

      {recommendations.map((rec, index) => (
        <div
          key={rec.theme}
          className={`rounded-xl border p-4 transition-all ${
            appliedTheme === rec.theme
              ? 'border-[rgb(var(--accent))] bg-[rgb(var(--accent-soft))] shadow-md'
              : 'border-[rgb(var(--line))] bg-[rgb(var(--surface-2))] hover:border-[rgb(var(--accent))]'
          }`}
        >
          <div className="flex items-start justify-between">
            <div>
              <h3 className="font-semibold text-[rgb(var(--ink))]">{rec.theme}</h3>
              <span className="text-xs text-[rgb(var(--muted))] capitalize">{rec.type.replace(/_/g, ' ')}</span>
            </div>
            <span className="text-sm font-medium text-[rgb(var(--ink))]">
              ${rec.estimatedCost.toLocaleString()}
            </span>
          </div>

          <p className="mt-2 text-sm text-[rgb(var(--muted))]">{rec.description}</p>

          {/* Color swatches */}
          <div className="mt-3 flex gap-2">
            {rec.colorScheme.map((color, i) => (
              <div
                key={i}
                className="h-6 w-6 rounded-full border border-[rgb(var(--line))] shadow-sm"
                style={{ backgroundColor: color }}
                title={color}
              />
            ))}
          </div>

          {/* Materials */}
          <div className="mt-2 flex flex-wrap gap-1">
            {rec.suggestedMaterials.map((mat) => (
              <span key={mat} className="rounded-full bg-[rgb(var(--surface))] px-2 py-0.5 text-xs text-[rgb(var(--muted))]">
                {mat}
              </span>
            ))}
          </div>

          {/* Apply button */}
          <button
            onClick={() => handleApplyTheme(rec)}
            className={`mt-3 w-full rounded-lg px-3 py-2 text-sm font-medium transition-colors ${
              appliedTheme === rec.theme
                ? 'bg-[rgb(var(--accent))] text-black'
                : 'bg-[rgb(var(--surface))] text-[rgb(var(--ink))] hover:bg-[rgb(var(--accent-soft))]'
            }`}
          >
            {appliedTheme === rec.theme ? '✓ Applied' : 'Apply Theme'}
          </button>
        </div>
      ))}
    </div>
  );
}
